import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
const exec = promisify(execFile);
const PORT = Number(process.env.SEMESTER_BRIDGE_PORT || 4317);
const VAULT = path.resolve(process.env.SEMESTER_VAULT || path.join(process.cwd(), "Semester Vault"));
const TYPES = new Set(["slides","lab","lab-report","worksheet","assignment","assignment-report","past-paper","formula-sheet","notes","other"]);
const safe = p => { const full = path.resolve(VAULT, p || "."); if (full !== VAULT && !full.startsWith(VAULT + path.sep)) throw new Error("Path is outside the configured vault"); return full; };
const json = (res, status, body) => { res.writeHead(status, {"content-type":"application/json","access-control-allow-origin":"*"}); res.end(JSON.stringify(body)); };
async function walk(dir, out = []) { for (const e of await fs.readdir(dir, {withFileTypes:true}).catch(() => [])) { const p=path.join(dir,e.name); if(e.isDirectory() && e.name !== ".semester-os") await walk(p,out); else if(e.isFile() && /\.pdf$/i.test(e.name)) out.push(p); } return out; }
function infer(abs) { const rel=path.relative(VAULT,abs); const parts=rel.split(path.sep); const module=parts[0] || "Uncategorised"; const raw=(parts[1]||"other").toLowerCase(); const aliases={slides:"slides",labs:"lab",worksheets:"worksheet",assignments:"assignment","past papers":"past-paper",notes:"notes"}; return {module,type:aliases[raw] || (TYPES.has(raw)?raw:"other")}; }
const INDEX = path.join(VAULT, ".semester-os", "index.json");
async function extract(abs) { try { const r=await exec("pdftotext",["-layout",abs,"-"]); return r.stdout; } catch { return ""; } }
function lightIndex(row){ const lines=(row.text||"").split(/\f|\n/).map(x=>x.trim()).filter(x=>x.length>3&&x.length<90); const topics=[]; for(const line of lines){if(topics.length>=12)break;if(/^[A-Z][A-Za-z0-9 ,()\-/]{4,}$/.test(line)&&!topics.some(t=>t.name.toLowerCase()===line.toLowerCase())) topics.push({name:line,startPage:1,endPage:Math.min(row.pages||1,3),confidence:.45});} return {schemaVersion:1,title:row.title,topics,keywords:[...new Set((row.text||"").toLowerCase().match(/\b[a-z][a-z-]{4,}\b/g)||[])].slice(0,20),shortDescription:lines.slice(0,2).join(" ").slice(0,220),generatedAt:new Date().toISOString(),provider:"deterministic-local"}; }
function pastQuestions(text,pages){const out=[];for(const [i,body] of text.split("\f").entries()){for(const line of body.split(/\n/)){const m=/^(?:question\s*)?(?:Q\s*)?(\d{1,2})(?:\s*[:.)]|\s*$)/i.exec(line.trim());if(!m)continue;const label=`Q${m[1]}`;if(out.some(q=>q.label===label))continue;const mark=/\((\d{1,3})\s*marks?\)|\[(\d{1,3})\s*marks?\]|(\d{1,3})\s*marks?/i.exec(body);out.push({id:label.toLowerCase(),label,startPage:i+1,endPage:Math.min(pages||text.split("\f").length,i+2),marks:mark?Number(mark[1]||mark[2]||mark[3]):undefined,topics:[],shortDescription:line.trim().slice(0,160)});}}return out;}
async function resources(reindex=false) { const files=await walk(VAULT); let old={}; try { old=JSON.parse(await fs.readFile(INDEX,"utf8")); } catch {} const rows=[]; for(const abs of files){ const st=await fs.stat(abs); const buf=await fs.readFile(abs); const hash=crypto.createHash("sha256").update(buf).digest("hex"); const prior=old[hash]; const {module,type}=infer(abs); let pages; try { const r=await exec("pdfinfo",[abs]); pages=Number(/Pages:\s+(\d+)/.exec(r.stdout)?.[1])||undefined; } catch {} const text=prior && !reindex ? prior.text : await extract(abs); const row={id:hash,path:path.relative(VAULT,abs),title:path.basename(abs,".pdf"),module,type,pages,modifiedAt:st.mtime.toISOString(),status:text?"indexed":"partial",text,topics:prior?.topics||[]}; rows.push(row); old[hash]=row; } await fs.mkdir(path.dirname(INDEX),{recursive:true}); await fs.writeFile(INDEX,JSON.stringify(old,null,2)); return rows; }
async function body(req){let s="";for await(const c of req)s+=c;return s;}
const server=http.createServer(async (req,res)=>{ try { const u=new URL(req.url,`http://127.0.0.1:${PORT}`); if(req.method==="OPTIONS"){res.writeHead(204,{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST","access-control-allow-headers":"content-type"});return res.end();} if(u.pathname==="/api/health") return json(res,200,{ok:true,vault:VAULT}); if(u.pathname==="/api/resources") return json(res,200,await resources()); if(u.pathname==="/api/file"){ const abs=safe(u.searchParams.get("path")); const st=await fs.stat(abs); res.writeHead(200,{"content-type":"application/pdf","content-length":st.size,"access-control-allow-origin":"*"}); return (await import("node:fs")).createReadStream(abs).pipe(res); } return json(res,404,{error:"Not found"}); } catch(e){ return json(res,400,{error:e.message}); }});
// Search is deliberately lexical and page-provenance preserving. It works without AI.
const oldHandler=server.listeners("request")[0]; server.removeListener("request",oldHandler); server.on("request",async(req,res)=>{try{const u=new URL(req.url,`http://127.0.0.1:${PORT}`);if(req.method==="OPTIONS"){res.writeHead(204,{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST","access-control-allow-headers":"content-type"});return res.end();}if(u.pathname==="/api/health")return json(res,200,{ok:true,vault:VAULT});if(u.pathname==="/api/resources")return json(res,200,await resources());if(u.pathname==="/api/reindex")return json(res,200,{resources:await resources(true)});if(u.pathname==="/api/search"){const q=(u.searchParams.get("q")||"").toLowerCase().trim();const rows=await resources();return json(res,200,rows.filter(r=>`${r.title} ${r.module} ${r.type} ${r.text}`.toLowerCase().includes(q)).map(r=>({...r,text:undefined,matchPage:Math.max(1,(r.text||"").toLowerCase().indexOf(q)>=0?((r.text||"").slice(0,(r.text||"").toLowerCase().indexOf(q)).match(/\f/g)||[]).length+1:1)})));}if(u.pathname==="/api/import"&&req.method==="POST"){const data=JSON.parse(await body(req));const rel=String(data.path||"");const source=safe(rel);const dest=safe(String(data.destination||path.basename(rel)));await fs.mkdir(path.dirname(dest),{recursive:true});await fs.copyFile(source,dest);return json(res,201,{ok:true,resource:(await resources()).find(r=>r.path===path.relative(VAULT,dest))});}if(u.pathname==="/api/file"){const abs=safe(u.searchParams.get("path"));const st=await fs.stat(abs);res.writeHead(200,{"content-type":"application/pdf","content-length":st.size,"access-control-allow-origin":"*"});return (await import("node:fs")).createReadStream(abs).pipe(res);}return json(res,404,{error:"Not found"});}catch(e){return json(res,400,{error:e.message});}});
await fs.mkdir(VAULT,{recursive:true}); server.listen(PORT,"127.0.0.1",()=>console.log(`Semester OS bridge listening on http://127.0.0.1:${PORT}\nVault: ${VAULT}`));
