/**
 * Emits db/seed/seed.sql from the typed seed data.
 *
 * Idempotent: uses deterministic ids and INSERT OR REPLACE so re-seeding never
 * duplicates rows. User-entered data lives in other tables and is untouched.
 *
 * Run with: npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  AUTUMN_2026_MODULES,
  SEED_AREAS,
  moduleUrl,
  type SeedAssessment,
} from "./autumn-2026.ts";

const q = (value: string | null | undefined): string =>
  value == null ? "NULL" : `'${value.replace(/'/g, "''")}'`;

const n = (value: number | null | undefined): string =>
  value == null ? "NULL" : String(value);

const b = (value: boolean | undefined): string => (value ? "1" : "0");

/** Deterministic id so re-running the seed updates rather than duplicates. */
const slug = (text: string): string =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);

const lines: string[] = [
  "-- Generated by db/seed/generate.ts -- do not edit by hand.",
  "-- Source: UCD public module descriptors, per build brief section 13,",
  "-- verified 25 Aug 2026. This is a source feed, not truth.",
  "",
];

for (const area of SEED_AREAS) {
  lines.push(
    `INSERT OR REPLACE INTO areas (id, name, is_university, color_token, sort_order) VALUES (${q(area.id)}, ${q(area.name)}, ${b(area.isUniversity)}, ${q(area.colorToken)}, ${area.sortOrder});`,
  );
}
lines.push("");

for (const m of AUTUMN_2026_MODULES) {
  const moduleId = m.code.toLowerCase();
  lines.push(
    `INSERT OR REPLACE INTO modules (id, code, name, credits, trimester, coordinator, ucd_url, syllabus_summary, student_effort_hours, assessment_profile, attendance_mandatory, color_token) VALUES (${q(moduleId)}, ${q(m.code)}, ${q(m.name)}, ${n(m.credits)}, ${q("Autumn 2026")}, ${q(m.coordinator || null)}, ${q(moduleUrl(m.code))}, ${q(m.syllabusSummary)}, ${n(m.studentEffortHours)}, ${q(m.assessmentProfile)}, ${b(m.attendanceMandatory)}, ${q(m.colorToken)});`,
  );

  for (const a of m.assessments as SeedAssessment[]) {
    const id = `${moduleId}-${slug(a.title)}`;
    // OR IGNORE, deliberately: assignment rows accumulate submission progress,
    // pinned real deadlines and user edits. Re-seeding must never clobber
    // those. Changed UCD values are the importer's job -- diff and confirm.
    lines.push(
      `INSERT OR IGNORE INTO assignments (id, module_id, title, assessment_type, weight_percent, due_week, due_week_end, is_exam, exam_minutes, source_url) VALUES (${q(id)}, ${q(moduleId)}, ${q(a.title)}, ${q(a.type)}, ${a.weight}, ${n(a.dueWeek)}, ${n(a.dueWeekEnd)}, ${b(a.isExam)}, ${n(a.examMinutes)}, ${q(moduleUrl(m.code))});`,
    );
  }
  lines.push("");
}

const outPath = join(dirname(fileURLToPath(import.meta.url)), "seed.sql");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote ${outPath} (${lines.length} lines)`);
